name: persian_fonts
description: A Flutter package for using free persian fonts. It supports Vazir, Samim, Shabnam and Sahel fonts.
version: 1.0.5
homepage: https://github.com/mahdyar/persian-fonts-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
   fonts:
      - family: hc_1
        fonts:
          - asset: lib/fonts/1-HC中文宋体.ttf
      - family: hc_2
        fonts:
          - asset: lib/fonts/2-HC中文黑体.ttf
      - family: hc_3
        fonts:
          - asset: lib/fonts/3-HC中文楷体.ttf
      - family: hc_4
        fonts:
          - asset: lib/fonts/4-HC中文隶体.ttf
      - family: hc_5
        fonts:
          - asset: lib/fonts/5-HC中文圆体.ttf
      - family: hc_6
        fonts:
          - asset: lib/fonts/6-HC中文草书.ttf
      - family: hc_7
        fonts:
          - asset: lib/fonts/7-HC手书写体.ttf
      - family: hc_8
        fonts:
          - asset: lib/fonts/8-HC蜡笔字体.ttf
      - family: hc_9
        fonts:
          - asset: lib/fonts/9-HC毡笔字体.ttf
      - family: hc_10
        fonts:
          - asset: lib/fonts/10-HC硬笔字体.ttf
      - family: hc_11
        fonts:
          - asset: lib/fonts/11-HC中文蝶语.ttf
      - family: hc_12
        fonts:
          - asset: lib/fonts/12-HC中文卡通.ttf
      - family: hc_13
        fonts:
          - asset: lib/fonts/13-HC幼儿字体.ttf
      - family: hc_14
        fonts:
          - asset: lib/fonts/14-HC启蒙字体.ttf
      - family: hc_15
        fonts:
          - asset: lib/fonts/15-HC中文倩体.ttf
      - family: hc_16
        fonts:
          - asset: lib/fonts/16-HC中文书魂.ttf
      - family: hc_17
        fonts:
          - asset: lib/fonts/17-HC中文细线.ttf
      - family: hc_18
        fonts:
          - asset: lib/fonts/18-HC中文稚语.ttf
      - family: hc_19
        fonts:
          - asset: lib/fonts/19-HC胖胖字体.ttf
      - family: hc_20
        fonts:
          - asset: lib/fonts/20-HC中文习字.ttf
      - family: hc_21
        fonts:
          - asset: lib/fonts/21-HC中文粗宋.ttf
      - family: hc_22
        fonts:
          - asset: lib/fonts/22-HC乐乐字体.ttf
      - family: hc_23
        fonts:
          - asset: lib/fonts/23-HC粗毛笔体.ttf
      - family: hc_24
        fonts:
          - asset: lib/fonts/24-HC圆印字体.ttf
      - family: hc_25
        fonts:
          - asset: lib/fonts/25-HC纂刻字体.ttf
      - family: hc_26
        fonts:
          - asset: lib/fonts/26-HC手书笔记.ttf
      - family: hc_27
        fonts:
          - asset: lib/fonts/27-HC圆交叠字.ttf
      - family: hc_28
        fonts:
          - asset: lib/fonts/28-HC春联毛笔.ttf
      - family: hc_29
        fonts:
          - asset: lib/fonts/29-HC圆点字体.ttf
      - family: hc_30
        fonts:
          - asset: lib/fonts/30-HC拼音粗楷.ttf
      - family: hc_32
        fonts:
          - asset: lib/fonts/32-HC舔舌字体.ttf
      - family: hc_33
        fonts:
          - asset: lib/fonts/33-HC毛笔行书.ttf
      - family: hc_34
        fonts:
          - asset: lib/fonts/34-HC绕线圈体.ttf
      - family: hc_35
        fonts:
          - asset: lib/fonts/35-HC黑边白字.ttf
      - family: hc_36
        fonts:
          - asset: lib/fonts/36-HC软滑橡胶.ttf
      - family: hc_37
        fonts:
          - asset: lib/fonts/37-HC滑水纹体.ttf
      - family: hc_38
        fonts:
          - asset: lib/fonts/38-HC童稚笔画.ttf
      - family: hc_39
        fonts:
          - asset: lib/fonts/39-HC童真字体.ttf
      - family: hc_40
        fonts:
          - asset: lib/fonts/40-HC精灵画笔.ttf
      - family: hc_41
        fonts:
          - asset: lib/fonts/41-HC印章字体.ttf