import 'package:flutter/material.dart';

// This file is automatically generated!

class HcFonts extends TextStyle {
  static const Hc_1 = TextStyle(fontFamily: 'hc_1', package: 'persian_fonts');

  static TextTheme hc1TextTheme = TextTheme(
    headline2: HcFonts.Hc_1,
    headline3: HcFonts.Hc_1,
    headline1: HcFonts.Hc_1,
    headline4: HcFonts.Hc_1,
    headline5: HcFonts.Hc_1,
    headline6: HcFonts.Hc_1,
    subtitle1: HcFonts.Hc_1,
    subtitle2: HcFonts.Hc_1,
    bodyText1: HcFonts.Hc_1,
    bodyText2: HcFonts.Hc_1,
    caption: HcFonts.Hc_1,
    button: HcFonts.Hc_1,
    overline: HcFonts.Hc_1,
  );

  static const Hc_2 = TextStyle(fontFamily: 'hc_2', package: 'persian_fonts');

  static TextTheme hc2TextTheme = TextTheme(
    headline2: HcFonts.Hc_2,
    headline3: HcFonts.Hc_2,
    headline1: HcFonts.Hc_2,
    headline4: HcFonts.Hc_2,
    headline5: HcFonts.Hc_2,
    headline6: HcFonts.Hc_2,
    subtitle1: HcFonts.Hc_2,
    subtitle2: HcFonts.Hc_2,
    bodyText1: HcFonts.Hc_2,
    bodyText2: HcFonts.Hc_2,
    caption: HcFonts.Hc_2,
    button: HcFonts.Hc_2,
    overline: HcFonts.Hc_2,
  );

  static const Hc_3 = TextStyle(fontFamily: 'hc_3', package: 'persian_fonts');

  static TextTheme hc3TextTheme = TextTheme(
    headline2: HcFonts.Hc_3,
    headline3: HcFonts.Hc_3,
    headline1: HcFonts.Hc_3,
    headline4: HcFonts.Hc_3,
    headline5: HcFonts.Hc_3,
    headline6: HcFonts.Hc_3,
    subtitle1: HcFonts.Hc_3,
    subtitle2: HcFonts.Hc_3,
    bodyText1: HcFonts.Hc_3,
    bodyText2: HcFonts.Hc_3,
    caption: HcFonts.Hc_3,
    button: HcFonts.Hc_3,
    overline: HcFonts.Hc_3,
  );
  static const Hc_4 = TextStyle(fontFamily: 'hc_4', package: 'persian_fonts');

  static TextTheme hc4TextTheme = TextTheme(
    headline2: HcFonts.Hc_4,
    headline3: HcFonts.Hc_4,
    headline1: HcFonts.Hc_4,
    headline4: HcFonts.Hc_4,
    headline5: HcFonts.Hc_4,
    headline6: HcFonts.Hc_4,
    subtitle1: HcFonts.Hc_4,
    subtitle2: HcFonts.Hc_4,
    bodyText1: HcFonts.Hc_4,
    bodyText2: HcFonts.Hc_4,
    caption: HcFonts.Hc_4,
    button: HcFonts.Hc_4,
    overline: HcFonts.Hc_4,
  );
  static const Hc_5 = TextStyle(fontFamily: 'hc_5', package: 'persian_fonts');

  static TextTheme hc5TextTheme = TextTheme(
    headline2: HcFonts.Hc_5,
    headline3: HcFonts.Hc_5,
    headline1: HcFonts.Hc_5,
    headline4: HcFonts.Hc_5,
    headline5: HcFonts.Hc_5,
    headline6: HcFonts.Hc_5,
    subtitle1: HcFonts.Hc_5,
    subtitle2: HcFonts.Hc_5,
    bodyText1: HcFonts.Hc_5,
    bodyText2: HcFonts.Hc_5,
    caption: HcFonts.Hc_5,
    button: HcFonts.Hc_5,
    overline: HcFonts.Hc_5,
  );
  static const Hc_6 = TextStyle(fontFamily: 'hc_6', package: 'persian_fonts');

  static TextTheme hc6TextTheme = TextTheme(
    headline2: HcFonts.Hc_6,
    headline3: HcFonts.Hc_6,
    headline1: HcFonts.Hc_6,
    headline4: HcFonts.Hc_6,
    headline5: HcFonts.Hc_6,
    headline6: HcFonts.Hc_6,
    subtitle1: HcFonts.Hc_6,
    subtitle2: HcFonts.Hc_6,
    bodyText1: HcFonts.Hc_6,
    bodyText2: HcFonts.Hc_6,
    caption: HcFonts.Hc_6,
    button: HcFonts.Hc_6,
    overline: HcFonts.Hc_6,
  );
  static const Hc_7 = TextStyle(fontFamily: 'hc_7', package: 'persian_fonts');

  static TextTheme hc7TextTheme = TextTheme(
    headline2: HcFonts.Hc_7,
    headline3: HcFonts.Hc_7,
    headline1: HcFonts.Hc_7,
    headline4: HcFonts.Hc_7,
    headline5: HcFonts.Hc_7,
    headline6: HcFonts.Hc_7,
    subtitle1: HcFonts.Hc_7,
    subtitle2: HcFonts.Hc_7,
    bodyText1: HcFonts.Hc_7,
    bodyText2: HcFonts.Hc_7,
    caption: HcFonts.Hc_7,
    button: HcFonts.Hc_7,
    overline: HcFonts.Hc_7,
  );
  static const Hc_8 = TextStyle(fontFamily: 'hc_8', package: 'persian_fonts');

  static TextTheme hc8TextTheme = TextTheme(
    headline2: HcFonts.Hc_8,
    headline3: HcFonts.Hc_8,
    headline1: HcFonts.Hc_8,
    headline4: HcFonts.Hc_8,
    headline5: HcFonts.Hc_8,
    headline6: HcFonts.Hc_8,
    subtitle1: HcFonts.Hc_8,
    subtitle2: HcFonts.Hc_8,
    bodyText1: HcFonts.Hc_8,
    bodyText2: HcFonts.Hc_8,
    caption: HcFonts.Hc_8,
    button: HcFonts.Hc_8,
    overline: HcFonts.Hc_8,
  );
  static const Hc_9 = TextStyle(fontFamily: 'hc_9', package: 'persian_fonts');

  static TextTheme hc9TextTheme = TextTheme(
    headline2: HcFonts.Hc_9,
    headline3: HcFonts.Hc_9,
    headline1: HcFonts.Hc_9,
    headline4: HcFonts.Hc_9,
    headline5: HcFonts.Hc_9,
    headline6: HcFonts.Hc_9,
    subtitle1: HcFonts.Hc_9,
    subtitle2: HcFonts.Hc_9,
    bodyText1: HcFonts.Hc_9,
    bodyText2: HcFonts.Hc_9,
    caption: HcFonts.Hc_9,
    button: HcFonts.Hc_9,
    overline: HcFonts.Hc_9,
  );
  static const Hc_10 = TextStyle(fontFamily: 'hc_10', package: 'persian_fonts');

  static TextTheme hc10TextTheme = TextTheme(
    headline2: HcFonts.Hc_10,
    headline3: HcFonts.Hc_10,
    headline1: HcFonts.Hc_10,
    headline4: HcFonts.Hc_1,
    headline5: HcFonts.Hc_10,
    headline6: HcFonts.Hc_10,
    subtitle1: HcFonts.Hc_10,
    subtitle2: HcFonts.Hc_10,
    bodyText1: HcFonts.Hc_10,
    bodyText2: HcFonts.Hc_10,
    caption: HcFonts.Hc_10,
    button: HcFonts.Hc_10,
    overline: HcFonts.Hc_10,
  );
  static const Hc_11 = TextStyle(fontFamily: 'hc_11', package: 'persian_fonts');

  static TextTheme hc11TextTheme = TextTheme(
    headline2: HcFonts.Hc_11,
    headline3: HcFonts.Hc_11,
    headline1: HcFonts.Hc_11,
    headline4: HcFonts.Hc_11,
    headline5: HcFonts.Hc_11,
    headline6: HcFonts.Hc_11,
    subtitle1: HcFonts.Hc_11,
    subtitle2: HcFonts.Hc_11,
    bodyText1: HcFonts.Hc_11,
    bodyText2: HcFonts.Hc_11,
    caption: HcFonts.Hc_11,
    button: HcFonts.Hc_11,
    overline: HcFonts.Hc_11,
  );
  static const Hc_12 = TextStyle(fontFamily: 'hc_12', package: 'persian_fonts');

  static TextTheme hc12TextTheme = TextTheme(
    headline2: HcFonts.Hc_12,
    headline3: HcFonts.Hc_12,
    headline1: HcFonts.Hc_12,
    headline4: HcFonts.Hc_12,
    headline5: HcFonts.Hc_12,
    headline6: HcFonts.Hc_12,
    subtitle1: HcFonts.Hc_12,
    subtitle2: HcFonts.Hc_12,
    bodyText1: HcFonts.Hc_12,
    bodyText2: HcFonts.Hc_12,
    caption: HcFonts.Hc_12,
    button: HcFonts.Hc_12,
    overline: HcFonts.Hc_12,
  );
  static const Hc_13 = TextStyle(fontFamily: 'hc_13', package: 'persian_fonts');

  static TextTheme hc13TextTheme = TextTheme(
    headline2: HcFonts.Hc_13,
    headline3: HcFonts.Hc_13,
    headline1: HcFonts.Hc_13,
    headline4: HcFonts.Hc_13,
    headline5: HcFonts.Hc_13,
    headline6: HcFonts.Hc_13,
    subtitle1: HcFonts.Hc_13,
    subtitle2: HcFonts.Hc_13,
    bodyText1: HcFonts.Hc_13,
    bodyText2: HcFonts.Hc_13,
    caption: HcFonts.Hc_13,
    button: HcFonts.Hc_13,
    overline: HcFonts.Hc_13,
  );
  static const Hc_14 = TextStyle(fontFamily: 'hc_14', package: 'persian_fonts');

  static TextTheme hc14TextTheme = TextTheme(
    headline2: HcFonts.Hc_14,
    headline3: HcFonts.Hc_14,
    headline1: HcFonts.Hc_14,
    headline4: HcFonts.Hc_14,
    headline5: HcFonts.Hc_14,
    headline6: HcFonts.Hc_14,
    subtitle1: HcFonts.Hc_14,
    subtitle2: HcFonts.Hc_14,
    bodyText1: HcFonts.Hc_14,
    bodyText2: HcFonts.Hc_14,
    caption: HcFonts.Hc_14,
    button: HcFonts.Hc_14,
    overline: HcFonts.Hc_14,
  );
  static const Hc_15 = TextStyle(fontFamily: 'hc_15', package: 'persian_fonts');

  static TextTheme hc15TextTheme = TextTheme(
    headline2: HcFonts.Hc_15,
    headline3: HcFonts.Hc_15,
    headline1: HcFonts.Hc_15,
    headline4: HcFonts.Hc_15,
    headline5: HcFonts.Hc_15,
    headline6: HcFonts.Hc_15,
    subtitle1: HcFonts.Hc_15,
    subtitle2: HcFonts.Hc_15,
    bodyText1: HcFonts.Hc_15,
    bodyText2: HcFonts.Hc_15,
    caption: HcFonts.Hc_15,
    button: HcFonts.Hc_15,
    overline: HcFonts.Hc_15,
  );
  static const Hc_16 = TextStyle(fontFamily: 'hc_16', package: 'persian_fonts');

  static TextTheme hc16TextTheme = TextTheme(
    headline2: HcFonts.Hc_16,
    headline3: HcFonts.Hc_16,
    headline1: HcFonts.Hc_16,
    headline4: HcFonts.Hc_16,
    headline5: HcFonts.Hc_16,
    headline6: HcFonts.Hc_16,
    subtitle1: HcFonts.Hc_16,
    subtitle2: HcFonts.Hc_16,
    bodyText1: HcFonts.Hc_16,
    bodyText2: HcFonts.Hc_16,
    caption: HcFonts.Hc_16,
    button: HcFonts.Hc_16,
    overline: HcFonts.Hc_16,
  );
  static const Hc_17 = TextStyle(fontFamily: 'hc_17', package: 'persian_fonts');

  static TextTheme hc17TextTheme = TextTheme(
    headline2: HcFonts.Hc_17,
    headline3: HcFonts.Hc_17,
    headline1: HcFonts.Hc_17,
    headline4: HcFonts.Hc_17,
    headline5: HcFonts.Hc_17,
    headline6: HcFonts.Hc_17,
    subtitle1: HcFonts.Hc_17,
    subtitle2: HcFonts.Hc_17,
    bodyText1: HcFonts.Hc_17,
    bodyText2: HcFonts.Hc_17,
    caption: HcFonts.Hc_17,
    button: HcFonts.Hc_17,
    overline: HcFonts.Hc_17,
  );
  static const Hc_18 = TextStyle(fontFamily: 'hc_18', package: 'persian_fonts');

  static TextTheme hc18TextTheme = TextTheme(
    headline2: HcFonts.Hc_18,
    headline3: HcFonts.Hc_18,
    headline1: HcFonts.Hc_18,
    headline4: HcFonts.Hc_18,
    headline5: HcFonts.Hc_18,
    headline6: HcFonts.Hc_18,
    subtitle1: HcFonts.Hc_18,
    subtitle2: HcFonts.Hc_18,
    bodyText1: HcFonts.Hc_18,
    bodyText2: HcFonts.Hc_18,
    caption: HcFonts.Hc_18,
    button: HcFonts.Hc_18,
    overline: HcFonts.Hc_18,
  );
  static const Hc_19 = TextStyle(fontFamily: 'hc_19', package: 'persian_fonts');

  static TextTheme hc19TextTheme = TextTheme(
    headline2: HcFonts.Hc_19,
    headline3: HcFonts.Hc_19,
    headline1: HcFonts.Hc_19,
    headline4: HcFonts.Hc_19,
    headline5: HcFonts.Hc_19,
    headline6: HcFonts.Hc_19,
    subtitle1: HcFonts.Hc_19,
    subtitle2: HcFonts.Hc_19,
    bodyText1: HcFonts.Hc_19,
    bodyText2: HcFonts.Hc_19,
    caption: HcFonts.Hc_19,
    button: HcFonts.Hc_19,
    overline: HcFonts.Hc_19,
  );
  static const Hc_20 = TextStyle(fontFamily: 'hc_20', package: 'persian_fonts');

  static TextTheme hc20TextTheme = TextTheme(
    headline2: HcFonts.Hc_20,
    headline3: HcFonts.Hc_20,
    headline1: HcFonts.Hc_20,
    headline4: HcFonts.Hc_20,
    headline5: HcFonts.Hc_20,
    headline6: HcFonts.Hc_20,
    subtitle1: HcFonts.Hc_20,
    subtitle2: HcFonts.Hc_20,
    bodyText1: HcFonts.Hc_20,
    bodyText2: HcFonts.Hc_20,
    caption: HcFonts.Hc_20,
    button: HcFonts.Hc_20,
    overline: HcFonts.Hc_20,
  );
  static const Hc_21 = TextStyle(fontFamily: 'hc_21', package: 'persian_fonts');

  static TextTheme hc21TextTheme = TextTheme(
    headline2: HcFonts.Hc_21,
    headline3: HcFonts.Hc_21,
    headline1: HcFonts.Hc_21,
    headline4: HcFonts.Hc_21,
    headline5: HcFonts.Hc_21,
    headline6: HcFonts.Hc_21,
    subtitle1: HcFonts.Hc_21,
    subtitle2: HcFonts.Hc_21,
    bodyText1: HcFonts.Hc_21,
    bodyText2: HcFonts.Hc_21,
    caption: HcFonts.Hc_21,
    button: HcFonts.Hc_21,
    overline: HcFonts.Hc_21,
  );
  static const Hc_22 = TextStyle(fontFamily: 'hc_22', package: 'persian_fonts');

  static TextTheme hc22TextTheme = TextTheme(
    headline2: HcFonts.Hc_22,
    headline3: HcFonts.Hc_22,
    headline1: HcFonts.Hc_22,
    headline4: HcFonts.Hc_22,
    headline5: HcFonts.Hc_22,
    headline6: HcFonts.Hc_22,
    subtitle1: HcFonts.Hc_22,
    subtitle2: HcFonts.Hc_22,
    bodyText1: HcFonts.Hc_22,
    bodyText2: HcFonts.Hc_22,
    caption: HcFonts.Hc_22,
    button: HcFonts.Hc_22,
    overline: HcFonts.Hc_22,
  );
  static const Hc_23 = TextStyle(fontFamily: 'hc_23', package: 'persian_fonts');

  static TextTheme hc23TextTheme = TextTheme(
    headline2: HcFonts.Hc_23,
    headline3: HcFonts.Hc_23,
    headline1: HcFonts.Hc_23,
    headline4: HcFonts.Hc_23,
    headline5: HcFonts.Hc_23,
    headline6: HcFonts.Hc_23,
    subtitle1: HcFonts.Hc_23,
    subtitle2: HcFonts.Hc_23,
    bodyText1: HcFonts.Hc_23,
    bodyText2: HcFonts.Hc_23,
    caption: HcFonts.Hc_23,
    button: HcFonts.Hc_23,
    overline: HcFonts.Hc_23,
  );
  static const Hc_24 = TextStyle(fontFamily: 'hc_24', package: 'persian_fonts');

  static TextTheme hc24TextTheme = TextTheme(
    headline2: HcFonts.Hc_24,
    headline3: HcFonts.Hc_24,
    headline1: HcFonts.Hc_24,
    headline4: HcFonts.Hc_24,
    headline5: HcFonts.Hc_24,
    headline6: HcFonts.Hc_24,
    subtitle1: HcFonts.Hc_24,
    subtitle2: HcFonts.Hc_24,
    bodyText1: HcFonts.Hc_24,
    bodyText2: HcFonts.Hc_24,
    caption: HcFonts.Hc_24,
    button: HcFonts.Hc_24,
    overline: HcFonts.Hc_24,
  );
  static const Hc_25 = TextStyle(fontFamily: 'hc_25', package: 'persian_fonts');

  static TextTheme hc25TextTheme = TextTheme(
    headline2: HcFonts.Hc_25,
    headline3: HcFonts.Hc_25,
    headline1: HcFonts.Hc_25,
    headline4: HcFonts.Hc_25,
    headline5: HcFonts.Hc_25,
    headline6: HcFonts.Hc_25,
    subtitle1: HcFonts.Hc_25,
    subtitle2: HcFonts.Hc_25,
    bodyText1: HcFonts.Hc_25,
    bodyText2: HcFonts.Hc_25,
    caption: HcFonts.Hc_25,
    button: HcFonts.Hc_25,
    overline: HcFonts.Hc_25,
  );
  static const Hc_26 = TextStyle(fontFamily: 'hc_26', package: 'persian_fonts');

  static TextTheme hc26TextTheme = TextTheme(
    headline2: HcFonts.Hc_26,
    headline3: HcFonts.Hc_26,
    headline1: HcFonts.Hc_26,
    headline4: HcFonts.Hc_26,
    headline5: HcFonts.Hc_26,
    headline6: HcFonts.Hc_26,
    subtitle1: HcFonts.Hc_26,
    subtitle2: HcFonts.Hc_26,
    bodyText1: HcFonts.Hc_26,
    bodyText2: HcFonts.Hc_26,
    caption: HcFonts.Hc_26,
    button: HcFonts.Hc_26,
    overline: HcFonts.Hc_26,
  );
  static const Hc_27 = TextStyle(fontFamily: 'hc_27', package: 'persian_fonts');

  static TextTheme hc27TextTheme = TextTheme(
    headline2: HcFonts.Hc_27,
    headline3: HcFonts.Hc_27,
    headline1: HcFonts.Hc_27,
    headline4: HcFonts.Hc_27,
    headline5: HcFonts.Hc_27,
    headline6: HcFonts.Hc_27,
    subtitle1: HcFonts.Hc_27,
    subtitle2: HcFonts.Hc_27,
    bodyText1: HcFonts.Hc_27,
    bodyText2: HcFonts.Hc_27,
    caption: HcFonts.Hc_27,
    button: HcFonts.Hc_27,
    overline: HcFonts.Hc_27,
  );
  static const Hc_28 = TextStyle(fontFamily: 'hc_28', package: 'persian_fonts');

  static TextTheme hc28TextTheme = TextTheme(
    headline2: HcFonts.Hc_28,
    headline3: HcFonts.Hc_28,
    headline1: HcFonts.Hc_28,
    headline4: HcFonts.Hc_28,
    headline5: HcFonts.Hc_28,
    headline6: HcFonts.Hc_28,
    subtitle1: HcFonts.Hc_28,
    subtitle2: HcFonts.Hc_28,
    bodyText1: HcFonts.Hc_28,
    bodyText2: HcFonts.Hc_28,
    caption: HcFonts.Hc_28,
    button: HcFonts.Hc_28,
    overline: HcFonts.Hc_28,
  );
  static const Hc_29 = TextStyle(fontFamily: 'hc_29', package: 'persian_fonts');

  static TextTheme hc29TextTheme = TextTheme(
    headline2: HcFonts.Hc_29,
    headline3: HcFonts.Hc_29,
    headline1: HcFonts.Hc_29,
    headline4: HcFonts.Hc_29,
    headline5: HcFonts.Hc_29,
    headline6: HcFonts.Hc_29,
    subtitle1: HcFonts.Hc_29,
    subtitle2: HcFonts.Hc_29,
    bodyText1: HcFonts.Hc_29,
    bodyText2: HcFonts.Hc_29,
    caption: HcFonts.Hc_29,
    button: HcFonts.Hc_29,
    overline: HcFonts.Hc_29,
  );
  static const Hc_30 = TextStyle(fontFamily: 'hc_30', package: 'persian_fonts');

  static TextTheme hc30TextTheme = TextTheme(
    headline2: HcFonts.Hc_30,
    headline3: HcFonts.Hc_30,
    headline1: HcFonts.Hc_30,
    headline4: HcFonts.Hc_30,
    headline5: HcFonts.Hc_30,
    headline6: HcFonts.Hc_30,
    subtitle1: HcFonts.Hc_30,
    subtitle2: HcFonts.Hc_30,
    bodyText1: HcFonts.Hc_30,
    bodyText2: HcFonts.Hc_30,
    caption: HcFonts.Hc_30,
    button: HcFonts.Hc_30,
    overline: HcFonts.Hc_30,
  );
  static const Hc_32 = TextStyle(fontFamily: 'hc_32', package: 'persian_fonts');

  static TextTheme hc32TextTheme = TextTheme(
    headline2: HcFonts.Hc_32,
    headline3: HcFonts.Hc_32,
    headline1: HcFonts.Hc_32,
    headline4: HcFonts.Hc_32,
    headline5: HcFonts.Hc_32,
    headline6: HcFonts.Hc_32,
    subtitle1: HcFonts.Hc_32,
    subtitle2: HcFonts.Hc_32,
    bodyText1: HcFonts.Hc_32,
    bodyText2: HcFonts.Hc_32,
    caption: HcFonts.Hc_32,
    button: HcFonts.Hc_32,
    overline: HcFonts.Hc_32,
  );

  static const Hc_33 = TextStyle(fontFamily: 'hc_33', package: 'persian_fonts');

  static TextTheme hc33TextTheme = TextTheme(
    headline2: HcFonts.Hc_33,
    headline3: HcFonts.Hc_33,
    headline1: HcFonts.Hc_33,
    headline4: HcFonts.Hc_33,
    headline5: HcFonts.Hc_33,
    headline6: HcFonts.Hc_33,
    subtitle1: HcFonts.Hc_33,
    subtitle2: HcFonts.Hc_33,
    bodyText1: HcFonts.Hc_33,
    bodyText2: HcFonts.Hc_33,
    caption: HcFonts.Hc_33,
    button: HcFonts.Hc_33,
    overline: HcFonts.Hc_33,
  );
  static const Hc_34 = TextStyle(fontFamily: 'hc_34', package: 'persian_fonts');

  static TextTheme hc34TextTheme = TextTheme(
    headline2: HcFonts.Hc_34,
    headline3: HcFonts.Hc_34,
    headline1: HcFonts.Hc_34,
    headline4: HcFonts.Hc_34,
    headline5: HcFonts.Hc_34,
    headline6: HcFonts.Hc_34,
    subtitle1: HcFonts.Hc_34,
    subtitle2: HcFonts.Hc_34,
    bodyText1: HcFonts.Hc_34,
    bodyText2: HcFonts.Hc_34,
    caption: HcFonts.Hc_34,
    button: HcFonts.Hc_34,
    overline: HcFonts.Hc_34,
  );
  static const Hc_35 = TextStyle(fontFamily: 'hc_35', package: 'persian_fonts');

  static TextTheme hc35TextTheme = TextTheme(
    headline2: HcFonts.Hc_35,
    headline3: HcFonts.Hc_35,
    headline1: HcFonts.Hc_35,
    headline4: HcFonts.Hc_35,
    headline5: HcFonts.Hc_35,
    headline6: HcFonts.Hc_35,
    subtitle1: HcFonts.Hc_35,
    subtitle2: HcFonts.Hc_35,
    bodyText1: HcFonts.Hc_35,
    bodyText2: HcFonts.Hc_35,
    caption: HcFonts.Hc_35,
    button: HcFonts.Hc_35,
    overline: HcFonts.Hc_35,
  );
  static const Hc_36 = TextStyle(fontFamily: 'hc_36', package: 'persian_fonts');

  static TextTheme hc36TextTheme = TextTheme(
    headline2: HcFonts.Hc_36,
    headline3: HcFonts.Hc_36,
    headline1: HcFonts.Hc_36,
    headline4: HcFonts.Hc_36,
    headline5: HcFonts.Hc_36,
    headline6: HcFonts.Hc_36,
    subtitle1: HcFonts.Hc_36,
    subtitle2: HcFonts.Hc_36,
    bodyText1: HcFonts.Hc_36,
    bodyText2: HcFonts.Hc_36,
    caption: HcFonts.Hc_36,
    button: HcFonts.Hc_36,
    overline: HcFonts.Hc_36,
  );
  static const Hc_37 = TextStyle(fontFamily: 'hc_37', package: 'persian_fonts');

  static TextTheme hc37TextTheme = TextTheme(
    headline2: HcFonts.Hc_37,
    headline3: HcFonts.Hc_37,
    headline1: HcFonts.Hc_37,
    headline4: HcFonts.Hc_37,
    headline5: HcFonts.Hc_37,
    headline6: HcFonts.Hc_37,
    subtitle1: HcFonts.Hc_37,
    subtitle2: HcFonts.Hc_37,
    bodyText1: HcFonts.Hc_37,
    bodyText2: HcFonts.Hc_37,
    caption: HcFonts.Hc_37,
    button: HcFonts.Hc_37,
    overline: HcFonts.Hc_37,
  );
  static const Hc_38 = TextStyle(fontFamily: 'hc_38', package: 'persian_fonts');

  static TextTheme hc38TextTheme = TextTheme(
    headline2: HcFonts.Hc_38,
    headline3: HcFonts.Hc_38,
    headline1: HcFonts.Hc_38,
    headline4: HcFonts.Hc_38,
    headline5: HcFonts.Hc_38,
    headline6: HcFonts.Hc_38,
    subtitle1: HcFonts.Hc_38,
    subtitle2: HcFonts.Hc_38,
    bodyText1: HcFonts.Hc_38,
    bodyText2: HcFonts.Hc_38,
    caption: HcFonts.Hc_38,
    button: HcFonts.Hc_38,
    overline: HcFonts.Hc_38,
  );
  static const Hc_39 = TextStyle(fontFamily: 'hc_39', package: 'persian_fonts');

  static TextTheme hc39TextTheme = TextTheme(
    headline2: HcFonts.Hc_39,
    headline3: HcFonts.Hc_39,
    headline1: HcFonts.Hc_39,
    headline4: HcFonts.Hc_39,
    headline5: HcFonts.Hc_39,
    headline6: HcFonts.Hc_39,
    subtitle1: HcFonts.Hc_39,
    subtitle2: HcFonts.Hc_39,
    bodyText1: HcFonts.Hc_39,
    bodyText2: HcFonts.Hc_39,
    caption: HcFonts.Hc_39,
    button: HcFonts.Hc_39,
    overline: HcFonts.Hc_39,
  );
/*
 Samim Font: https://github.com/rastikerdar/samim-font
*/

  static const Hc_40 = TextStyle(fontFamily: 'hc_40', package: 'persian_fonts');

  static TextTheme samimTextTheme = TextTheme(
    headline2: HcFonts.Hc_40,
    headline3: HcFonts.Hc_40,
    headline1: HcFonts.Hc_40,
    headline4: HcFonts.Hc_40,
    headline5: HcFonts.Hc_40,
    headline6: HcFonts.Hc_40,
    subtitle1: HcFonts.Hc_40,
    subtitle2: HcFonts.Hc_40,
    bodyText1: HcFonts.Hc_40,
    bodyText2: HcFonts.Hc_40,
    caption: HcFonts.Hc_40,
    button: HcFonts.Hc_40,
    overline: HcFonts.Hc_40,
  );

/*
 Shabnam Font: https://github.com/rastikerdar/shabnam-font
*/

  static const Hc_41 = TextStyle(fontFamily: 'hc_41', package: 'persian_fonts');

  static TextTheme shabnamTextTheme = TextTheme(
    headline2: HcFonts.Hc_41,
    headline3: HcFonts.Hc_41,
    headline1: HcFonts.Hc_41,
    headline4: HcFonts.Hc_41,
    headline5: HcFonts.Hc_41,
    headline6: HcFonts.Hc_41,
    subtitle1: HcFonts.Hc_41,
    subtitle2: HcFonts.Hc_41,
    bodyText1: HcFonts.Hc_41,
    bodyText2: HcFonts.Hc_41,
    caption: HcFonts.Hc_41,
    button: HcFonts.Hc_41,
    overline: HcFonts.Hc_41,
  );
}
